import type { JournalEntry } from '../types';

export const SAMPLE_INITIAL_ENTRIES: JournalEntry[] = [
  {
    id: 'entry_public_1',
    userId: 'public',
    title: 'Cultivating Calm Amidst Architectural Complexities',
    createdAt: Date.now() - 3600 * 1000 * 4,
    updatedAt: Date.now() - 3600 * 1000 * 4,
    dateString: new Date(Date.now() - 3600 * 1000 * 4).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    }),
    rawTranscript: 'Reflected on managing cognitive load when working on complex software systems. Learned to embrace the Stoic dichotomy of control.',
    messages: [
      {
        id: 'm1',
        role: 'user',
        content: 'Today felt overwhelming with multiple system architectures in flight. I found myself worrying about things outside my direct influence.',
        timestamp: '10:15 AM',
      },
      {
        id: 'm2',
        role: 'model',
        content: 'It is natural to feel friction when balancing intricate variables. In Stoic philosophy, clarity begins when we draw a boundary between what is in our control (our focused attention, our craft, our reaction) and what lies outside it (external timeline shifts, unpredictable blockers). What is one concrete priority you can own fully today?',
        timestamp: '10:16 AM',
        modelUsed: 'gemini-3.5-flash',
      },
      {
        id: 'm3',
        role: 'user',
        content: 'I can focus purely on writing clean, modular components and ensuring tests pass. Once I committed to that, the mental fog lifted.',
        timestamp: '10:18 AM',
      },
    ],
    summary: 'Explored strategies to decouple emotional reactivity from systemic complexity. Focused on establishing clear cognitive boundaries and deliberate task execution.',
    keyTakeaways: [
      'Separate internal agency from external system noise.',
      'Single-task focus produces superior clarity compared to fractured attention.',
      'Small, structured milestones diminish cognitive fatigue.',
    ],
    gratitudeOrWins: [
      'Grateful for dedicated focus time this morning.',
      'Successfully untangled a complex modular data pipeline.',
    ],
    actionableSteps: [
      'Timebox deep focus blocks to 45 minutes.',
      'Conduct a 5-minute end-of-day reflection before stepping away from the desk.',
    ],
    sentiment: 'Positive',
    sentimentScore: 0.72,
    confidence: 94,
    tags: ['Mindfulness', 'Architecture', 'Resilience', 'Focus'],
    emotionalEnergy: 'Calm / Grounded',
    primaryEmotion: 'Serenity & Purpose',
    reflectionPromptForTomorrow: 'Where can you simplify friction before it compounds tomorrow?',
    wordCount: 142,
    turnCount: 3,
  },
  {
    id: 'entry_public_2',
    userId: 'public',
    title: 'Creative Insights from Ambient Evening Walk',
    createdAt: Date.now() - 3600 * 1000 * 28,
    updatedAt: Date.now() - 3600 * 1000 * 28,
    dateString: new Date(Date.now() - 3600 * 1000 * 28).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    }),
    rawTranscript: 'A dusk stroll through the park sparked new ideas on user interface typography, contrast, and subtle motion design.',
    messages: [
      {
        id: 'm1_2',
        role: 'user',
        content: 'Took a sunset walk without headphones. The gradient of the twilight sky made me think about subtle color transitions in UI design.',
        timestamp: '7:40 PM',
      },
      {
        id: 'm2_2',
        role: 'model',
        content: 'Observation without digital distraction frequently reveals organic harmony. Natural twilight blends cool obsidian with lavender and deep blues with optical balance. How might you translate that quiet harmony into your digital workspaces?',
        timestamp: '7:41 PM',
        modelUsed: 'gemini-3.1-pro-preview',
      },
    ],
    summary: 'Captured creative reflections during an offline walk, deriving visual inspiration from atmospheric lighting to enhance user interface palettes.',
    keyTakeaways: [
      'Unstructured quiet time is essential for novel conceptual synthesis.',
      'Natural gradients provide better mathematical contrast cues than synthetic saturated colors.',
    ],
    gratitudeOrWins: [
      'Witnessed a peaceful sunset over the skyline.',
      'Experienced a breakthrough in color harmony for the dark mode canvas.',
    ],
    actionableSteps: [
      'Maintain an offline walking routine twice weekly.',
      'Document natural color pairings in a visual sketchbook.',
    ],
    sentiment: 'Positive',
    sentimentScore: 0.88,
    confidence: 96,
    tags: ['Creativity', 'Design', 'Nature', 'Inspiration'],
    emotionalEnergy: 'High / Energized',
    primaryEmotion: 'Creative Flow',
    reflectionPromptForTomorrow: 'What natural pattern can you observe tomorrow to inspire your work?',
    wordCount: 110,
    turnCount: 2,
  },
  {
    id: 'entry_public_3',
    userId: 'public',
    title: 'Socratic Inquiry: Re-evaluating Productivity Metrics',
    createdAt: Date.now() - 3600 * 1000 * 54,
    updatedAt: Date.now() - 3600 * 1000 * 54,
    dateString: new Date(Date.now() - 3600 * 1000 * 54).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    }),
    rawTranscript: 'Questioned the habit of equating sheer volume of output with meaningful progress. Realigned around deep craft.',
    messages: [
      {
        id: 'm1_3',
        role: 'user',
        content: 'I noticed I was checking off low-impact checklist items just to feel busy, rather than tackling the foundational problems.',
        timestamp: '2:15 PM',
      },
      {
        id: 'm2_3',
        role: 'model',
        content: 'A profound realization. Socrates often pressed his peers on whether their actions were aimed at the appearance of virtue or its essence. When you substitute velocity for directional significance, what fears or frictions are being avoided?',
        timestamp: '2:16 PM',
        modelUsed: 'gemini-3.5-flash',
      },
    ],
    summary: 'Deconstructed the illusion of busywork through Socratic inquiry. Re-anchored daily work around high-leverage craftsmanship over shallow task volume.',
    keyTakeaways: [
      'Velocity without clarity is merely rapid drift.',
      'Prioritize one foundational milestone each morning before administrative tasks.',
    ],
    gratitudeOrWins: [
      'Recognized the trap of superficial productivity early in the week.',
    ],
    actionableSteps: [
      'Identify the single most impactful lever each evening for the next day.',
    ],
    sentiment: 'Neutral',
    sentimentScore: 0.25,
    confidence: 91,
    tags: ['Philosophy', 'Productivity', 'Self-Awareness', 'Socratic'],
    emotionalEnergy: 'Moderate / Steady',
    primaryEmotion: 'Clarity & Realism',
    reflectionPromptForTomorrow: 'Are your actions tomorrow serving depth or merely motion?',
    wordCount: 128,
    turnCount: 2,
  },
];
